### PR TITLE
Initial support for Scala.js

### PR DESCRIPTION
**Pull request by dwijnand**
There's a bunch of fallout but, given I've solved large chunks and identified the underlying causes of some of the others, I thought I'd share this.

### CODE REVIEW

**Comment by paulp** [comment]
Thanks! It's nice to see that as always people are ridiculously glib by imagining there is any chance whatsoever it will just work. I sometimes wonder if most of the people who talk about programming ever do any programming at all.

For a variety of reasons I'm not going to merge this at this moment, but I'll leave it open and it has already been useful in giving me a sense of what will affect scala-js compatibility.

**Comment by dwijnand** [comment]
It was an interesting exercise, a bit more sbt wrangling then I expected, and a number of Scala.js issues I'd never seen before (not that I do Scala.js often).

And while I do agree that people tend to talk more than do (a trap I've fallen into too often) I think you underestimate how uniquely broad and feature-full your code is compared to the vast majority, so hitting several fringe cases makes sense. Or maybe I just think that because my experience recently has been of mostly small or small-scoped projects.

Also how much your build setup diverges from the beaten path makes for more wrangling then generally required - but it's given me an idea for a more linear structure, without fighting sbt's defaults so much. I'm going to try inverting the structure, see how well it works, and propose it for review.

**Comment by paulp** [comment]
A visual depiction of the fringe cases in scala.
or-3

And I have no dependencies! How much worse must it be for a typical scala project, which in my experience has three or more?

**Comment by dwijnand** [comment]
Feel free to ping me whenever you're ready to add this.

**Pull request closed without merging**
