### PR TITLE
Kill Show[Vdex] by making Vindex ShowSelf

### PR DESCRIPTION
**Pull request by dwijnand**
I was looking at how much `ShowDirect` and `ShowSelf` were used nowadays, to see if either or both could also go, and in doing so simultaneously gained more understanding of and appreciation for typeclasses, and understood better what is meant by "when a Show type class is more trouble than it's worth".

But then `Vdex`/`Vindex` looked like an outlier, with its own hand-crafted `Show` instance, instead of going through `Show[ShowDirect]` like all the other self-describable types in std.

### CODE REVIEW

**Comment by paulp** [comment]
Well. The way it's supposed to work is that `Nth(2).pp` is `"2"` or more likely `"#2"` and `Index(1).pp` is `"1"`. It's not possible to accomplish that if it uses ShowSelf because the representation of those two instances is identical - only via the type can they be distinguished.

With some fiddling I can get it working as described, at least under favorable conditions:
```scala
psp> Nth(1).pp
res12: String = 1

psp> Nth(1).indexValue.pp
res13: String = 0

psp> Index(0).pp
res14: String = 0

psp> Index(0).indexValue.pp
res15: String = 0
```

However this comes at a steep price:
```scala
psp> (Nth(1): Vdex).pp
res17: String = psp.std.Vindex@0
```
Because if there is a Show[Vdex] instance, even at an explicitly lower priority, scala's wheels come off.
```scala
// Given the existence of
implicit def showVdex: Show[Vdex] = by(_.indexValue)

// We get
[error] /g/psp-std/std/src/main/scala/std/Native.scala:363: type mismatch;
[error]  found   : psp.std.Vindex[_$1] where type _$1
[error]  required: psp.std.Doc
[error]     case Slice(s, len)  => view((s + len.getLong - 1) |> (e => pp"$s-$e"))
[error]                                                                    ^
[error] /g/psp-std/std/src/main/scala/std/Native.scala:363: type mismatch;
[error]  found   : psp.std.Vindex[_$1]
[error]  required: psp.std.Doc
[error]     case Slice(s, len)  => view((s + len.getLong - 1) |> (e => pp"$s-$e"))
[error]                                                                       ^
[error] /g/psp-std/std/src/main/scala/std/Native.scala:366: type mismatch;
[error]  found   : psp.std.Vindex[_$1] where type _$1
[error]  required: psp.std.Doc
[error]     case All(s)         => view(pp"$s-")
[error]                                     ^
```

**Comment by paulp** [comment]
Mmm, I figured that out. Such a clusterfuck of broken. Naturally the error message has absolutely zero to do with the problem. It's an implicit ambiguity of course. Once one massages it into sharing what is the actual problem, we find it considers these ambiguous:
```
  implicit def showPrimitive[A >: Primitive <: AnyVal] : Show[A] = Show.Inherited
  implicit def showVdex[A]: Show[Vindex[A]]                      = by(_.indexValue)
```
Of course when I bound a type parameter by `AnyVal` I want to include all the primitive types and also whatever user defined value classes there are, like Vindex, because there are so many useful methods which can be written which operate on that subset of types.

Both the upper bound and lower bound on `showPrimitive` are there in the hopes of excluding the user-defined classes from consideration and even in combination they cannot do it.

**Comment by dwijnand** [comment]
Just for context, at the time of this change there was no low priority `Show[Nth]` ([added later](https://github.com/paulp/psp-std/commit/d742dace563dfbaaefb34d485d7d29e2e4cbd0fc#diff-743cc814d0a1a971174b5db531b8e317)), and I didn't fully grasp the intent until I saw your LambdaConf slides.

But I did review this change recently and noticed that things were still work in progress, given the current head of master has this behaviour:

```scala
psp> Nth(1).pp
res2: String = 0

psp> Nth(1).indexValue.pp
res3: String = 0

psp> Index(0).pp
res4: String = 0

psp> Index(0).indexValue.pp
res5: String = 0

psp> (Nth(1): Vdex).pp
res6: String = 0
```

Also, what's the difference intended between `.pp` and `.show`?

**Comment by dwijnand** [comment]
Anyways, removing Show[Vdex] the right thing to do.

**Pull request closed without merging**
