### PR TITLE
Extract psp-show & related changes.

### PR DESCRIPTION
**Pull request by dwijnand**
Specifically:
* std: Move Label into its own file
* dmz: Steal 3 methods from psp.std
* dmz: Steal 2 methods from PspStringOps, introduce DmzStringOps
* std: Lose psp.std.repl.show, moved to consoleOnly
* Misc minor changes

Happy to revist any of this. Also, feel free to cherry-pick what you want in
and I'll pickup the difference and drop or rework it.

### CODE REVIEW

**Comment by dwijnand** [comment]
Oh and left a comment with the commented out pieces of Show that didn't make it to psp-show, can either live with that and remove noise, or find/decide a way to have them exist there.

**Comment by dwijnand** [comment]
Rebased onto master, squashed a couple of commits together & cleaned up DmzStringOps.

**Comment by paulp** [comment]
I am keen to take advantage of your interest in improving psp-std, but I need to do something about my works in progress before I let things diverge any further because to do nothing is to abandon them. (That's what the spire patch was.) Also, I need to better articulate why dmz exists. I'm going to close this for now but it would be great if you'd reopen it after I work on this a bit. You did succeed in drawing me back into it for long enough to tie off some loose ends.

**Comment by dwijnand** [comment]
That's fine (success!). I'll hold onto these. Ping back when you've synced everything up and have opened shop again.

**Pull request closed without merging**
