### PR TITLE
Cross-build against Scala 2.13.0-M3

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Something seems to be up with the integration between GitHub and Travis CI on this repo.

Please note the build for this PR went green:
✅ https://travis-ci.org/paulp/psp-std/builds/338863713

**Comment by dwijnand** [comment]
Review by @paulp?

**Comment by dwijnand** [comment]
The patch is trivial, and also it partially disables scoverage. So no need to keep this open.

**Comment by paulp** [comment]
The scoverage argument is a good one. I'm not super 2.13 motivated as yet in any case, I might need to be educated about what it will buy me at this point.

**Comment by dwijnand** [comment]
The reason I started down this road was an interest to see how well (or not) your code dealt with changes in 2.13. Turned out it all worked, so I shared the branch.

But the new collections will land in M4, so that'll probably be the more interesting experiment.

**Pull request closed without merging**
