### PR TITLE
Bump to 2.12.0-M5

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Pending https://github.com/rickynils/scalacheck/pull/248 and release.

**Comment by dwijnand** [comment]
Travis rebuild pls

**Comment by dwijnand** [comment]
Alternatively https://github.com/scala-js/scala-2.12-junit-mixin-plugin could be used.. WDYT?

**Comment by paulp** [comment]
I am deathly allergic to plugins if there is any conceivable alternative. They are little storehouses of future suffering.

**Pull request merged**
