### PR TITLE
Use Initialize#apply instead of enriched mapValue

### PR DESCRIPTION
**Pull request by dwijnand**
The method you've been looking for..

Also - welcome back!

### CODE REVIEW

**Comment by paulp** [comment]
But whyyyy doesn't map work?

**Comment by paulp** [comment]
Man, codecov borders on useless. Strictly by removing code, you've reduced coverage! It's a miracle!

**Comment by dwijnand** [comment]
I can only share my conjectures:

1. map returns a Task to bias towards lazy evaluation; if you really want to evaluate now reach for apply instead
2. because of the unification of settings and tasks map returns tasks for both (including via tuple enrichments), and apply is only on setting and returns setting (or tuple of settings)

**Comment by paulp** [comment]
> map returns a Task to bias towards lazy evaluation; if you really want to evaluate now reach for apply instead

"Now" is somebody else's notion. I just want to turn an `F[A]` into an `F[B]`. That's what we call map! Everywhere except sbt settings and the standard library I guess.

**Comment by dwijnand** [comment]
I guess I never took the opportunity to say: I find the fact that it uses apply to be bizarre and unintuitive.

**Comment by paulp** [comment]
@dwijnand that's reassuring to hear anyway. It's such an odd place to choose to violate the most basic of expectations.

**Pull request merged**
